import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import NewNavbar from "@/components/NewNavbar";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen font-sans antialiased grain relative",
            inter.className
          )}
        >
          <SignedIn>
            <NewNavbar />
          </SignedIn>
          <SignedOut>
            <Navbar />
          </SignedOut>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
